import { makeStyles, createStyles } from "@mui/styles";

export const useStyles = makeStyles(() =>
  createStyles({
    heroSection: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
      background: "white",
      color: "white",
      textAlign: "center",
      paddingTop: "70px",
      paddingBottom: "70px",
      "& .highlight": {
        color: "#1976d2",
      },
    },
    title: {
      fontSize: "4rem",
      width: "70%",
      margin: 0,
      color: "#333",
      lineHeight: "1.2",
      fontWeight: "600",
      "@media (max-width: 768px)": {
        fontSize: "2.5rem",
        width: "90%",
      },
    },
    subtitle: {
      fontSize: "1.5rem",
      fontWeight: 300,
      width: "60%",
      margin: "30px 0",
      color: "#555",
      lineHeight: "1.5",
      "@media (max-width: 768px)": {
        fontSize: "1.2rem",
        width: "90%",
      },
    },
    ctaButton: {
      backgroundColor: "#1976d2 !important",
      color: "#fff !important",
      padding: "12px 24px !important",
      fontSize: "1.2rem !important",
      borderRadius: "6px !important",
      boxShadow: "0 2px 10px rgba(25, 118, 210, 0.2) !important",
      transition: "all 0.3s ease-in-out !important",
      "&:hover": {
        backgroundColor: "#fff !important",
        color: "#1976d2 !important",
        outline: "#1976d2 solid 1px !important",
        transform: "translateY(-2px) !important",
        boxShadow: "0 4px 12px rgba(25, 118, 210, 0.3) !important",
      },
    },
    secondaryButton: {
      backgroundColor: "#fff !important",
      color: "#1976d2 !important",
      padding: "12px 24px !important",
      fontSize: "1.2rem !important",
      border: "1px solid #1976d2 !important",
      borderRadius: "6px !important",
      transition: "all 0.3s ease-in-out !important",
      "&:hover": {
        backgroundColor: "#1976d2 !important",
        color: "#fff !important",
        transform: "translateY(-2px) !important",
        boxShadow: "0 4px 12px rgba(25, 118, 210, 0.2) !important",
      },
    },
    yellowButton: {
      backgroundColor: "#ea9c0d !important",
      color: "#333 !important",
      padding: "12px 24px !important",
      fontSize: "1.2rem !important",
      borderRadius: "6px !important",
      boxShadow: "0 2px 10px rgba(234, 156, 13, 0.3) !important",
      transition: "all 0.3s ease-in-out !important",
      "&:hover": {
        backgroundColor: "#fff !important",
        color: "#ea9c0d !important",
        border: "1px solid #ea9c0d !important",
        transform: "translateY(-2px) !important",
      },
    },
    contentSection: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
      background: "linear-gradient(135deg, #1976d2, #0d47a1)",
      color: "white",
      textAlign: "center",
      padding: "80px 0",
      borderRadius: "10px",
      boxShadow: "0 10px 30px rgba(0, 0, 0, 0.1)",
      margin: "20px 0",
      "& .highlight": {
        color: "#1976d2",
      },
    },
    contentTitle: {
      fontSize: "2.2rem",
      color: "#fff",
      textAlign: "left",
      width: "80%",
      margin: "20px auto",
      fontWeight: "600",
      "@media (max-width: 1200px)": {
        fontSize: "1.5rem",
        width: "90%",
      },
    },
    contentDescription: {
      color: "#fff",
      width: "80%",
      margin: "0 auto",
      textAlign: "left",
      fontSize: "1.5rem",
      lineHeight: "1.6",
      "@media (max-width: 1200px)": {
        fontSize: "1.2rem",
        width: "90%",
      },
    },
    fullWidthBox: {
      display: "flex",
      flexDirection: "row",
      width: "100%",
      marginBottom: "40px",
      "@media (max-width: 1400px)": {
        flexDirection: "column",
      },
    },
    imageSection: {
      flex: 2,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      marginRight: "20px",
      padding: "20px",
      "@media (max-width: 1400px)": {
        marginRight: 0,
        padding: "20px",
        order: 2,
      },
    },
    descriptionSection: {
      flex: 1,
      padding: "20px",
      "@media (max-width: 1400px)": {
        order: 1,
      },
    },
    featuresSection: {
      padding: "100px 0",
      background: "#fff",
      textAlign: "center",
      width: "100%",
      "& h2": {
        fontSize: "2.5rem",
        marginBottom: "10px",
        color: "#333",
      },
      "& h4": {
        fontSize: "1.2rem",
        marginBottom: "50px",
        color: "#666",
      },
    },
    featureContainer: {
      display: "flex",
      justifyContent: "center",
      alignItems: "flex-start",
      margin: "40px auto",
      gap: "100px",
      maxWidth: "1200px",
      padding: "0 20px",
      "@media (max-width: 768px)": {
        flexDirection: "column",
        margin: "20px auto",
        gap: "40px",
        padding: "0 20px",
      },
    },
    featureItem: {
      flex: 1,
      padding: "30px",
      maxWidth: "350px",
      borderRadius: "8px",
      transition: "transform 0.3s ease, box-shadow 0.3s ease",
      "&:hover": {
        transform: "translateY(-10px)",
        boxShadow: "0 10px 30px rgba(0, 0, 0, 0.08)",
      },
      "@media (max-width: 768px)": {
        maxWidth: "100%",
      },
    },
    featureIcon: {
      fontSize: "3rem",
      color: "#1976d2",
      textAlign: "left",
      margin: "0 0 15px 0",
    },
    featureTitle: {
      marginTop: "20px",
      fontSize: "1.5rem",
      color: "#333",
      textAlign: "left",
      fontWeight: "600",
    },
    featureDescription: {
      color: "#666",
      textAlign: "left",
      lineHeight: "1.6",
      marginTop: "10px",
    },
    ctaSection: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
      background: "#fff",
      color: "white",
      textAlign: "center",
      padding: "80px 0",
      "& .highlight": {
        color: "#1976d2",
      },
    },
    footer: {
      padding: "60px 0",
      background: "#fff",
      color: "#000",
      textAlign: "left",
      display: "grid",
      gridTemplateColumns: "2fr 1fr 1fr 1fr 1fr",
      gap: "20px",
      borderTop: "1px solid #eee",
      "@media (max-width: 768px)": {
        gridTemplateColumns: "1fr",
        textAlign: "center",
        padding: "40px 20px",
      },
    },
    footerColumn: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      textAlign: "center",
    },
    footerTitle: {
      marginBottom: "15px",
      color: "#333",
      fontWeight: "600",
    },
    footerLink: {
      color: "#555",
      textDecoration: "none",
      marginBottom: "10px",
      transition: "color 0.2s ease",
      "&:hover": {
        color: "#1976d2",
        textDecoration: "none",
      },
    },
    logoButton: {
      backgroundColor: "transparent !important",
      color: "#1976d2 !important",
      padding: "10px 20px !important",
      fontSize: "2rem !important",
      outline: "none !important",
      boxShadow: "none !important",
      fontWeight: "bold !important",
      display: "flex !important",
      alignItems: "center !important",
      minWidth: "fit-content !important",
      "& img": {
        width: "75px !important",
        height: "60px !important",
        marginBottom: "10px !important",
      },
    },
    buttonContainer: {
      display: "flex",
      justifyContent: "space-between",
      width: "400px",
      flexWrap: "wrap",
      margin: "20px 0 30px",
      gap: "15px",
      "@media (max-width: 500px)": {
        width: "100%",
        justifyContent: "center",
      },
    },
    mainImage: {
      marginTop: "80px",
      maxWidth: "50%",
      height: "auto",
      transition: "transform 0.5s ease",
      "&:hover": {
        transform: "scale(1.02)",
      },
      "@media (max-width: 768px)": {
        maxWidth: "90%",
      },
    },
    imageGrid: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: "50px",
      width: "90%",
      maxWidth: "1400px",
      margin: "0 auto",
      paddingTop: "60px",
      paddingBottom: "20px",
    },
    imageRow: {
      display: "flex",
      justifyContent: "center",
      gap: "40px",
      width: "100%",
      "@media (min-width: 1400px)": {
        gap: "80px",
      },
      "@media (max-width: 1024px)": {
        flexWrap: "wrap",
        gap: "20px",
      },
      "@media (max-width: 600px)": {
        flexDirection: "column",
        alignItems: "center",
      },
    },
    gridImage: {
      height: "80px",
      width: "auto",
      padding: "10px",
      transition: "transform 0.3s ease",
      "&:hover": {
        transform: "scale(1.1)",
      },
    },
    responsiveImage: {
      backgroundColor: "#FFE7BB",
      padding: "20px",
      borderRadius: "12px",
      width: "100%",
      boxShadow: "0 8px 20px rgba(0, 0, 0, 0.08)",
      transition: "transform 0.3s ease",
      "&:hover": {
        transform: "translateY(-5px)",
      },
      "& img": {
        width: "100%",
        height: "auto",
        maxHeight: "700px",
        minHeight: "500px",
        borderRadius: "10px",
        objectFit: "contain",
        "@media (max-width: 1200px)": {
          maxHeight: "500px",
          minHeight: "350px",
        },
        "@media (max-width: 700px)": {
          maxHeight: "300px",
          minHeight: "200px",
        },
      },
      "@media (max-width: 1400px)": {
        padding: "20px",
      },
    },
  }),
);
