import { makeStyles, createStyles } from "@mui/styles";
import type { Theme } from "@mui/material";

export const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    heroSection: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
      background: "white",
      color: "white",
      textAlign: "center",
      paddingTop: "70px",
      paddingBottom: "70px",
      "& .highlight": {
        color: theme.palette.primary.light || "#1976d2",
      },
    },
    title: {
      fontSize: "4rem",
      width: "70%",
      margin: 0,
      color: "#333",
      lineHeight: "1.2",
      fontWeight: "600",
      "@media (max-width: 768px)": {
        fontSize: "2.5rem",
        width: "90%",
      },
    },
    subtitle: {
      fontSize: "1.5rem",
      fontWeight: 300,
      width: "60%",
      margin: "30px 0",
      color: "#555",
      lineHeight: "1.5",
      "@media (max-width: 768px)": {
        fontSize: "1.2rem",
        width: "90%",
      },
    },
    ctaButton: {
      "&.MuiButton-root": {
        backgroundColor: theme.palette.primary.light || "#1976d2",
        color: "#fff",
        padding: "12px 24px",
        fontSize: "1.2rem",
        borderRadius: "6px",
        boxShadow: "0 2px 10px rgba(25, 118, 210, 0.2)",
        transition: "all 0.3s ease-in-out",
        "&:hover": {
          backgroundColor: "#fff",
          color: theme.palette.primary.light || "#1976d2",
          outline: `${theme.palette.primary.light || "#1976d2"} solid 1px`,
          transform: "translateY(-2px)",
          boxShadow: "0 4px 12px rgba(25, 118, 210, 0.3)",
        },
      },
    },
    secondaryButton: {
      "&.MuiButton-root": {
        backgroundColor: "#fff",
        color: theme.palette.primary.light || "#1976d2",
        padding: "12px 24px",
        fontSize: "1.2rem",
        border: `1px solid ${theme.palette.primary.light || "#1976d2"}`,
        borderRadius: "6px",
        transition: "all 0.3s ease-in-out",
        "&:hover": {
          backgroundColor: theme.palette.primary.light || "#1976d2",
          color: "#fff",
          transform: "translateY(-2px)",
          boxShadow: "0 4px 12px rgba(25, 118, 210, 0.2)",
        },
      },
    },
    yellowButton: {
      "&.MuiButton-root": {
        backgroundColor: "#ea9c0d",
        color: "#333",
        padding: "12px 24px",
        fontSize: "1.2rem",
        borderRadius: "6px",
        boxShadow: "0 2px 10px rgba(234, 156, 13, 0.3)",
        transition: "all 0.3s ease-in-out",
        "&:hover": {
          backgroundColor: "#fff",
          color: "#ea9c0d",
          border: "1px solid #ea9c0d",
          transform: "translateY(-2px)",
        },
      },
    },
    contentSection: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
      background: "linear-gradient(135deg, #1976d2, #0d47a1)",
      color: "white",
      textAlign: "center",
      padding: "80px 0",
      borderRadius: "10px",
      boxShadow: "0 10px 30px rgba(0, 0, 0, 0.1)",
      margin: "20px 0",
      "& .highlight": {
        color: theme.palette.primary.light || "#1976d2",
      },
    },
    contentTitle: {
      fontSize: "2.2rem",
      color: "#fff",
      textAlign: "left",
      width: "80%",
      margin: "20px auto",
      fontWeight: "600",
      "@media (max-width: 1200px)": {
        fontSize: "1.5rem",
        width: "90%",
      },
    },
    contentDescription: {
      color: "#fff",
      width: "80%",
      margin: "0 auto",
      textAlign: "left",
      fontSize: "1.5rem",
      lineHeight: "1.6",
      "@media (max-width: 1200px)": {
        fontSize: "1.2rem",
        width: "90%",
      },
    },
    fullWidthBox: {
      display: "flex",
      flexDirection: "row",
      width: "100%",
      marginBottom: "40px",
      "@media (max-width: 1400px)": {
        flexDirection: "column",
      },
    },
    imageSection: {
      flex: 2,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      marginRight: "20px",
      padding: "20px",
      "@media (max-width: 1400px)": {
        marginRight: 0,
        padding: "20px",
        order: 2,
      },
    },
    descriptionSection: {
      flex: 1,
      padding: "20px",
      "@media (max-width: 1400px)": {
        order: 1,
      },
    },
    featuresSection: {
      padding: "100px 0",
      background: "#fff",
      textAlign: "center",
      width: "100%",
      "& h2": {
        fontSize: "2.5rem",
        marginBottom: "10px",
        color: "#333",
      },
      "& h4": {
        fontSize: "1.2rem",
        marginBottom: "50px",
        color: "#666",
      },
    },
    featureContainer: {
      display: "flex",
      justifyContent: "center",
      alignItems: "flex-start",
      margin: "40px auto",
      gap: "100px",
      maxWidth: "1200px",
      padding: "0 20px",
      "@media (max-width: 768px)": {
        flexDirection: "column",
        margin: "20px auto",
        gap: "40px",
        padding: "0 20px",
      },
    },
    featureItem: {
      flex: 1,
      padding: "30px",
      maxWidth: "350px",
      borderRadius: "8px",
      transition: "transform 0.3s ease, box-shadow 0.3s ease",
      "&:hover": {
        transform: "translateY(-10px)",
        boxShadow: "0 10px 30px rgba(0, 0, 0, 0.08)",
      },
      "@media (max-width: 768px)": {
        maxWidth: "100%",
      },
    },
    featureIcon: {
      fontSize: "3rem",
      color: theme.palette.primary.light || "#1976d2",
      textAlign: "left",
      margin: "0 0 15px 0",
    },
    featureTitle: {
      marginTop: "20px",
      fontSize: "1.5rem",
      color: "#333",
      textAlign: "left",
      fontWeight: "600",
    },
    featureDescription: {
      color: "#666",
      textAlign: "left",
      lineHeight: "1.6",
      marginTop: "10px",
    },
    compatibilitySection: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      marginTop: "60px",
      marginBottom: "40px",
      padding: "0 20px",
    },
    compatibilityTitle: {
      fontSize: "3rem",
      color: "#333",
      marginBottom: "20px",
      textAlign: "center",
      fontWeight: "600",
    },
    compatibilityDescription: {
      fontSize: "1.4rem",
      color: "#666",
      marginBottom: "50px",
      textAlign: "center",
      maxWidth: "1000px",
    },
    compatibilityGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(3, minmax(300px, 1fr))",
      gap: "30px",
      width: "100%",
      maxWidth: "1400px",
      "@media (max-width: 1200px)": {
        gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
      },
      "@media (max-width: 768px)": {
        gridTemplateColumns: "1fr",
      },
    },
    compatibilityCard: {
      backgroundColor: "#f8f9fa",
      borderRadius: "10px",
      padding: "30px",
      boxShadow: "0 4px 15px rgba(0, 0, 0, 0.05)",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "space-between",
      transition: "transform 0.3s ease, box-shadow 0.3s ease",
      border: "1px solid #eaeaea",
      height: "100%",
      "&:hover": {
        transform: "translateY(-8px)",
        boxShadow: "0 8px 25px rgba(0, 0, 0, 0.1)",
        borderColor: theme.palette.primary.light || "#1976d2",
      },
    },
    cardTitle: {
      fontSize: "1.8rem",
      color: "#333",
      marginBottom: "25px",
      textAlign: "center",
      fontWeight: "600",
      position: "relative",
      paddingBottom: "15px",
      "&:after": {
        content: '""',
        position: "absolute",
        bottom: 0,
        left: "50%",
        transform: "translateX(-50%)",
        width: "60px",
        height: "3px",
        backgroundColor: theme.palette.primary.light || "#1976d2",
      },
    },
    cardLogos: {
      display: "flex",
      flexWrap: "wrap",
      justifyContent: "center",
      alignItems: "center",
      gap: "25px",
      marginTop: "15px",
    },
    cardLogo: {
      height: "80px",
      width: "auto",
      maxWidth: "140px",
      objectFit: "contain",
      transition: "transform 0.3s ease",
      "&:hover": {
        transform: "scale(1.1)",
      },
    },
    ctaSection: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
      background: "#fff",
      color: "white",
      textAlign: "center",
      padding: "80px 0",
      "& .highlight": {
        color: theme.palette.primary.light || "#1976d2",
      },
    },
    footer: {
      padding: "60px 0",
      background: "#fff",
      color: "#000",
      textAlign: "left",
      display: "grid",
      gridTemplateColumns: "2fr 1fr 1fr 1fr 1fr",
      gap: "20px",
      borderTop: "1px solid #eee",
      "@media (max-width: 768px)": {
        gridTemplateColumns: "1fr",
        textAlign: "center",
        padding: "40px 20px",
      },
    },
    footerColumn: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      textAlign: "center",
    },
    footerTitle: {
      marginBottom: "15px",
      color: "#333",
      fontWeight: "600",
    },
    footerLink: {
      color: "#555",
      textDecoration: "none",
      marginBottom: "10px",
      transition: "color 0.2s ease",
      "&:hover": {
        color: theme.palette.primary.light || "#1976d2",
        textDecoration: "none",
      },
    },
    logoButton: {
      "&.MuiButton-root": {
        backgroundColor: "transparent",
        color: theme.palette.primary.light || "#1976d2",
        padding: "10px 20px",
        fontSize: "2rem",
        outline: "none",
        boxShadow: "none",
        fontWeight: "bold",
        display: "flex",
        alignItems: "center",
        minWidth: "fit-content",
        "& img": {
          width: "75px",
          height: "60px",
          marginBottom: "10px",
        },
      },
    },
    buttonContainer: {
      display: "flex",
      justifyContent: "space-between",
      width: "400px",
      flexWrap: "wrap",
      margin: "20px 0 30px",
      gap: "15px",
      "@media (max-width: 500px)": {
        width: "100%",
        justifyContent: "center",
      },
    },
    mainImage: {
      marginTop: "80px",
      maxWidth: "50%",
      height: "auto",
      transition: "transform 0.5s ease",
      "&:hover": {
        transform: "scale(1.02)",
      },
      "@media (max-width: 768px)": {
        maxWidth: "90%",
      },
    },
    imageGrid: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: "70px",
      width: "100%",
      maxWidth: "1600px",
      margin: "0 auto",
      paddingTop: "60px",
      paddingBottom: "40px",
    },
    categorySection: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      marginBottom: "30px",
    },
    categoryHeading: {
      fontSize: "2rem",
      color: "#333",
      marginBottom: "30px",
      position: "relative",
      fontWeight: "600",
      "&:after": {
        content: '""',
        position: "absolute",
        bottom: "-12px",
        left: "50%",
        transform: "translateX(-50%)",
        width: "70px",
        height: "4px",
        backgroundColor: theme.palette.primary.light || "#1976d2",
      },
    },
    imageRow: {
      display: "flex",
      justifyContent: "center",
      gap: "60px",
      width: "100%",
      "@media (min-width: 1400px)": {
        gap: "100px",
      },
      "@media (max-width: 1024px)": {
        flexWrap: "wrap",
        gap: "40px",
      },
      "@media (max-width: 600px)": {
        flexDirection: "column",
        alignItems: "center",
        gap: "30px",
      },
    },
    gridImage: {
      height: "120px",
      width: "auto",
      maxWidth: "240px",
      objectFit: "contain",
      padding: "15px",
      transition: "transform 0.3s ease",
      "&:hover": {
        transform: "scale(1.1)",
      },
    },
    responsiveImage: {
      backgroundColor: "#FFE7BB",
      padding: "20px",
      borderRadius: "12px",
      width: "100%",
      boxShadow: "0 8px 20px rgba(0, 0, 0, 0.08)",
      transition: "transform 0.3s ease",
      "&:hover": {
        transform: "translateY(-5px)",
      },
      "& img": {
        width: "100%",
        height: "auto",
        maxHeight: "700px",
        minHeight: "500px",
        borderRadius: "10px",
        objectFit: "contain",
        "@media (max-width: 1200px)": {
          maxHeight: "500px",
          minHeight: "350px",
        },
        "@media (max-width: 700px)": {
          maxHeight: "300px",
          minHeight: "200px",
        },
      },
      "@media (max-width: 1400px)": {
        padding: "20px",
      },
    },
  }),
);
