# optimised compose specefic for e2e testing

services:
  bitcoind:
    image: lncm/bitcoind:v27.0
    container_name: caravan_e2e_bitcoind_ci
    ports:
      - "18443:18443"
    command: >
      -server
      -regtest
      -rpcuser=${BITCOIN_RPC_USER}
      -rpcpassword=${BITCOIN_RPC_PASSWORD}
      -rpcbind=0.0.0.0:18443
      -rpcallowip=127.0.0.1
      -rpcallowip=172.16.0.0/12
      -rpcallowip=192.168.0.0/16
      -fallbackfee=0.0002
      -minrelaytxfee=0.00000001
      -debug=0
      -printtoconsole=1
      -disablewallet=0
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "bitcoin-cli",
          "-regtest",
          "-rpcuser=${BITCOIN_RPC_USER}",
          "-rpcpassword=${BITCOIN_RPC_PASSWORD}",
          "getblockchaininfo",
        ]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 15s
    networks:
      - caravan-e2e-ci
    tmpfs:
      - /tmp
    shm_size: 128m
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"

  nginx:
    image: nginx:alpine
    container_name: caravan-e2e-nginx-ci
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      bitcoind:
        condition: service_healthy
    networks:
      - caravan-e2e-ci
    # Faster startup
    tmpfs:
      - /var/cache/nginx
      - /var/run
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
  caravan:
    build:
      context: ../../../
      dockerfile: apps/coordinator/Dockerfile
      target: runner
      # CI build optimizations
      cache_from:
        - caravanbitcoin/coordinator:latest
    container_name: caravan_coordinator_ci
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    depends_on:
      bitcoind:
        condition: service_healthy
      nginx:
        condition: service_started
    networks:
      - caravan-e2e-ci
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 3s
      timeout: 2s
      retries: 6
      start_period: 10s
    # Don't restart in CI
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"

networks:
  caravan-e2e-ci:
    driver: bridge
