name: Publish container image

on:
  workflow_dispatch:
  push:
    tags:
      - '@caravan/coordinator**'
    branches:
      - main

jobs:
  push_to_registry:
    name: Push container image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: caravanbitcoin/caravan

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/coordinator/Dockerfile
          push: true
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
