name: 'Close Inactive PRs'

# Trigger the workflow on a schedule (e.g., daily at 1:30 AM UTC)
on:
  schedule:
    - cron: '30 1 * * *'
  # Optional: Allow manual triggering for testing
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v9.1.0
        with:
          # Disable stale marking for issues by setting to -1
          days-before-issue-stale: -1
          days-before-issue-close: -1
          # Configure PR settings
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-message: >
            This pull request has been inactive for 30 days and has been marked as stale.
            It will be closed in 7 days if no further activity occurs. To keep this PR open,
            add the "long-lived" label or comment on it.
          close-pr-message: >
            This pull request has been automatically closed due to inactivity for 7 days
            after being marked as stale. Feel free to reopen if needed!
          stale-pr-label: 'stale'
          exempt-pr-labels: 'long-lived'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
